services:
  - type: web
    name: email-campaign-admin
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: email-campaign-db
          property: connectionString

databases:
  - name: email-campaign-db
    databaseName: email_campaign_admin
    user: email_campaign_user
    plan: free 